# Setup
title: Mehdi Munim # Remplacez par votre nom ou le titre de votre site
tagline: Ingénieur en IA et Formateur # Remplacez par votre tagline
description: >- # Remplacez par la description de votre site
  Ingénieur en IA & formateur.
url: https://mehdimunim.github.io # Remplacez par l'URL de votre site
baseurl: "" # Laissez vide si vous utilisez le domaine par défaut de GitHub Pages
paginate: 5
permalink: pretty

# About/contact
author:
  name: Mehdi Munim # Remplacez par votre nom
  url: https://www.linkedin.com/in/mehdimunim # Remplacez par votre URL LinkedIn
  email: mehdi.munim@gmail.com # Remplacez par votre email

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0
google_analytics_id: # UA-XXXX-Y (optionnel)
